#Build a Java 8 Executable Image
# syntax=docker/dockerfile:1
FROM openjdk:8 as javaApp
WORKDIR /java
COPY Java8-1.0-SNAPSHOT.jar /java/Java8-1.0-SNAPSHOT.jar
#not really needed but will use later
EXPOSE 8080
CMD java -jar /java/Java8-1.0-SNAPSHOT.jar

#Build an image for an Oracle Express DB
FROM container-registry.oracle.com/database/express:18.4.0-xe as oracleDB
COPY --from=javaApp /java/Java8-1.0-SNAPSHOT.jar /java/Java8-1.0-SNAPSHOT.jar